#!/bin/sh
# Reconstruit le harnais : expose au navigateur de test les fonctions internes de l'app.
# DANS LE DÉPÔT, et plus dans un dossier temporaire : le harnais avait déjà été perdu une
# fois avec l'environnement, emportant des dizaines de tests écrits au fil du projet.
SRC=${SRC:-/home/user/alize-work/index.html}
OUT=${OUT:-/home/user/alize-work/tests/harn/app.html}
sed 's/function render(){/function render(){window.__S=S;window.__render=render;window.__setFB=function(v){FB=v;};/
     s/^  function fbErrTxt(e){/  window.__err=function(e){return fbErrTxt(e);};\n  function fbErrTxt(e){/
     s/^  function newMission(svc){/  window.__newMission=function(s){return newMission(s);};\n  function newMission(svc){/
     s/^  function molliePeutTravailler(){/  window.__peutTravailler=function(){return molliePeutTravailler();};window.__differe=function(){return versementDiffere();};\n  function molliePeutTravailler(){/
     s/^  function adminLedgerGroups(){/  window.__ledgerTotal=function(){var l=adminCommissionLedger();return {lignes:l.length,commission:l.reduce(function(t,e){return t+(e.commissionAmount||0);},0)};};\n  function adminLedgerGroups(){/
     s/^  function srvMontants(src){/  window.__rev={srv:function(x){return srvMontants(x);},recale:function(h,r){return recaleHist(h,r);},record:function(m){return recordProPaid(m);}};\n  function srvMontants(src){/
     s/^  function tarifsRecapHtml(){/  window.__tarifs={feuille:function(){return tarifsRecapHtml();},metier:function(i){return tarifDuMetier(i);},marque:function(i){return tarifMarque(i);},defauts:function(){return ADMIN_PRICES();}};\n  function tarifsRecapHtml(){/
     s/^  function parcoursClients(clients,parClient,maintenant){/  window.__parcours=function(c,p,m){return parcoursClients(c,p,m);};\n  function parcoursClients(clients,parClient,maintenant){/
     s/^  function jalonClient(cle){/  window.__jalon=function(c){return jalonClient(c);};\n  function jalonClient(cle){/
     s/^  function activeServicesFromArtisans(){/  window.__dispo=function(){return activeServicesFromArtisans();};\n  function activeServicesFromArtisans(){/
     s/^  function parcoursPro(drafts){/  window.__pro={parcours:function(d){return parcoursPro(d);},jalons:function(f){return jalonsProDe(f);},etapes:function(){return PRO_ETAPES;}};\n  function parcoursPro(drafts){/
     s/^  function catalogGroups(id){/  window.__cat={list:function(i){return catalogFor(i);},groups:function(i){return catalogGroups(i);}};\n  function catalogGroups(id){/
     s/^  function admSeenGet(){/  window.__adm={artNew:function(a){return admArtNew(a);},cliNew:function(c){return admCliNew(c);},thNew:function(t){return admThreadNew(t);},seen:function(k,v){return admSeenSet(k,v);},artSig:function(a){return admArtSig(a);},cliSig:function(c){return admCliSig(c);},count:function(){return adminNewCount();}};\n  function admSeenGet(){/
     s/^  function tryVisibleBackLink(){/  window.__back=function(){return goBack();};\n  function tryVisibleBackLink(){/
     s/^  function accepterDemo(m){/  window.__demo={accepte:function(m){return accepterDemo(m);},estExamen:function(){return isReviewDemo();}};\n  function accepterDemo(m){/
     s/^  function icoValide(k){/  window.__svc={ico:function(i){return svcIco(i);},valide:function(k){return icoValide(k);},choix:function(){return SVC_ICOS;},ajoute:function(n,r,c){return addCustomService(n,r,c);},trouve:function(i){return findSvc(i);},relit:function(d){return applyCatalogDoc(d);},table:function(){return I;},renomme:function(i,v){return renommerMetier(i,v);},nom:function(i){return nomCourant(i);},liste:function(){return nomsEnListe();},defaut:function(i){return nomDeCode(i);}};\n  function icoValide(k){/
     s/^  function noterInstallation(){/  window.__inst={systeme:function(){return demanderAuSysteme();},seCite:function(){return manifesteSeCite();},guide:function(o){return showInstallGuide(o);},tel:function(){return telConnu();}};\n  function noterInstallation(){/
     s/^  function majSansRisque(){/  window.__maj={sansRisque:function(){return majSansRisque();}};\n  function majSansRisque(){/
     s/^  function lireBrouillon(){/  window.__brouillon={lire:function(){return lireBrouillon();},oublier:function(){return oublierBrouillon();},cle:function(){return brouillonCle();}};\n  function lireBrouillon(){/
     s/^  function adminSetCat(a,sv,on){/  window.__art={cat:function(a,s,o){return adminSetCat(a,s,o);},ouverts:function(){return activeServicesFromArtisans();},fiche:function(a){return artCatsEditor(a);}};\n  function adminSetCat(a,sv,on){/
     s/^  function prixAutreLu(brut){/  window.__prix={lu:function(b){return prixAutreLu(b);},avis:function(b,u){return prixAutreAvis(b,u);},carte:function(n,p,u,a,b,c){return autrePrixCard(n,p,u,a,b,c);},okAutre:function(f){return autrePrixOk(f);},manque:function(f){return proMissing(f);}};\n  function prixAutreLu(brut){/
     s/^  function changerStatutArtisan(a,etat){/  window.__statut={changer:function(a,e){return changerStatutArtisan(a,e);},carte:function(a){return carteStatutArtisan(a);},etats:function(){return ART_STATUTS;},fid:function(a){return carteFideliteArtisan(a);},palier:function(a,c){return changerFideliteArtisan(a,c);},amb:function(a,o){return changerAmbassadeurArtisan(a,o);},mien:function(){return monPalier();},taux:function(){return myCommPct();},autre:function(a){return autreDemandeActes(a);},nom:function(t){return autreNomPropose(t);}};\n  function changerStatutArtisan(a,etat){/
     s/^  function insPeutValider(a){/  window.__assur={champ:function(f){return champAssurance(f);},etat:function(a){return insStatus(a);},etiquette:function(st){return insLabel(st);},peutValider:function(a){return insPeutValider(a);},etape:function(f){return draftInsDone(f);},complet:function(f){return proSignupOk(f);},manque:function(f){return proMissing(f);},etapes:function(f){return draftSteps(f);},suite:function(c){return nextDraftStep(c);},manqueEtape:function(e,f){return manqueEtape(e,f);},faites:function(f){return {id:draftIdDone(f),ins:draftInsDone(f),svc:draftSvcDone(f),acc:draftAccDone(f)};}};\n  function insPeutValider(a){/
     s/^  function sauverBrouillonCloud(j){/  window.__dossier={cloud:function(j){return sauverBrouillonCloud(j);},fusion:function(c){return fusionnerBrouillonCloud(c);},enregistre:function(){return saveProDraft();},charge:function(){return loadProDraft();},cle:function(){return proDraftKey();},oublie:function(){return oublierBrouillonCloud();},max:function(){return PRO_DRAFT_PHOTO_MAX;}};\n  function sauverBrouillonCloud(j){/
     s/^  function telLu(pfx,num){/  window.__tel={lu:function(p,n){return telLu(p,n);},stocke:function(p){return telStockeLu(p);},avis:function(p,n){return telAvis(p,n);},console:function(p){return telImpossibleTxt(p);},coupe:function(p){return splitPhone(p);}};\n  function telLu(pfx,num){/
     s/^  function murSousLigne(f){/  window.__murs={sous:function(f){return murSousLigne(f);},qui:function(q,m){return murQuiHtml(q,m);},depuis:function(){return CLIENT_JALONS_DEPUIS;}};\n  function murSousLigne(f){/
     s/^  function i18nApply(root){/  window.__tr=function(v,lang){var av=S.lang;S.lang=lang;try{return trOne(v);}finally{S.lang=av;}};window.__dict=function(lang){return lang===String.fromCharCode(112,116)?PT_DICT:EN_DICT;};\n  function i18nApply(root){/' \
  "$SRC" > "$OUT"
for f in __S __render __err __newMission __peutTravailler __tr __adm __cat __rev __demo __back __svc __art __brouillon __inst __maj __dossier __assur __prix __statut __tel __murs __parcours; do
  grep -q "window.$f" "$OUT" || { echo "MANQUE $f"; exit 1; }
done
echo "harnais complet"
